# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Nanking Cigar
subtitle:
description:
keywords: 'Cigar, Nanking Cigar, Chao, Chao Yang, Hexo, NexT'
author: Nanking Cigar
language: 
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.nankingcigar.ml
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:nankingcigar/nankingcigar.github.io.git
  branch: master

feed:
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content: true
  #content_limit: 140
  #content_limit_delim: ' '

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

# filter_optimize:
#   enable: true
#   remove_query_string: true
#   remove_comments: true
#   css:
#     enable: true
#     bundle: true
#     delivery: true
#     inlines:
#     excludes: ['/lib/font-awesome/css/font-awesome.min.css']
#   js:
#     bundle: true
#     excludes:
#   priority: 12

service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true

theme_config:
  custom:
    post_end_tage:
      enabled: true
    copyright:
      enabled: true
    daovoice:
      enabled: true
      app_id: 6b442712